language: java

install: mvn clean install

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - davide.bolognini@gmail.com
      - alessandro.berra@gmail.com
    on_success: change
    on_failure: always	
